# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo1.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(442, 145)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.bpLayout = QtWidgets.QHBoxLayout()
        self.bpLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.bpLayout.setObjectName("bpLayout")
        self.mbpLayout = QtWidgets.QHBoxLayout()
        self.mbpLayout.setObjectName("mbpLayout")
        self.m_bp_1 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m_bp_1.sizePolicy().hasHeightForWidth())
        self.m_bp_1.setSizePolicy(sizePolicy)
        self.m_bp_1.setMinimumSize(QtCore.QSize(32, 32))
        self.m_bp_1.setMaximumSize(QtCore.QSize(32, 32))
        self.m_bp_1.setText("")
        self.m_bp_1.setObjectName("m_bp_1")
        self.mbpLayout.addWidget(self.m_bp_1)
        self.m_bp_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m_bp_2.sizePolicy().hasHeightForWidth())
        self.m_bp_2.setSizePolicy(sizePolicy)
        self.m_bp_2.setMinimumSize(QtCore.QSize(32, 32))
        self.m_bp_2.setMaximumSize(QtCore.QSize(32, 32))
        self.m_bp_2.setText("")
        self.m_bp_2.setObjectName("m_bp_2")
        self.mbpLayout.addWidget(self.m_bp_2)
        self.m_bp_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m_bp_3.sizePolicy().hasHeightForWidth())
        self.m_bp_3.setSizePolicy(sizePolicy)
        self.m_bp_3.setMinimumSize(QtCore.QSize(32, 32))
        self.m_bp_3.setMaximumSize(QtCore.QSize(32, 32))
        self.m_bp_3.setText("")
        self.m_bp_3.setObjectName("m_bp_3")
        self.mbpLayout.addWidget(self.m_bp_3)
        self.m_bp_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m_bp_4.sizePolicy().hasHeightForWidth())
        self.m_bp_4.setSizePolicy(sizePolicy)
        self.m_bp_4.setMinimumSize(QtCore.QSize(32, 32))
        self.m_bp_4.setMaximumSize(QtCore.QSize(32, 32))
        self.m_bp_4.setText("")
        self.m_bp_4.setObjectName("m_bp_4")
        self.mbpLayout.addWidget(self.m_bp_4)
        self.m_bp_5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m_bp_5.sizePolicy().hasHeightForWidth())
        self.m_bp_5.setSizePolicy(sizePolicy)
        self.m_bp_5.setMinimumSize(QtCore.QSize(32, 32))
        self.m_bp_5.setMaximumSize(QtCore.QSize(32, 32))
        self.m_bp_5.setText("")
        self.m_bp_5.setObjectName("m_bp_5")
        self.mbpLayout.addWidget(self.m_bp_5)
        self.bpLayout.addLayout(self.mbpLayout)
        self.ebpLayout = QtWidgets.QHBoxLayout()
        self.ebpLayout.setObjectName("ebpLayout")
        self.e_bp_1 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.e_bp_1.sizePolicy().hasHeightForWidth())
        self.e_bp_1.setSizePolicy(sizePolicy)
        self.e_bp_1.setMinimumSize(QtCore.QSize(32, 32))
        self.e_bp_1.setMaximumSize(QtCore.QSize(32, 32))
        self.e_bp_1.setText("")
        self.e_bp_1.setObjectName("e_bp_1")
        self.ebpLayout.addWidget(self.e_bp_1)
        self.e_bp_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.e_bp_2.sizePolicy().hasHeightForWidth())
        self.e_bp_2.setSizePolicy(sizePolicy)
        self.e_bp_2.setMinimumSize(QtCore.QSize(32, 32))
        self.e_bp_2.setMaximumSize(QtCore.QSize(32, 32))
        self.e_bp_2.setText("")
        self.e_bp_2.setObjectName("e_bp_2")
        self.ebpLayout.addWidget(self.e_bp_2)
        self.e_bp_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.e_bp_3.sizePolicy().hasHeightForWidth())
        self.e_bp_3.setSizePolicy(sizePolicy)
        self.e_bp_3.setMinimumSize(QtCore.QSize(32, 32))
        self.e_bp_3.setMaximumSize(QtCore.QSize(32, 32))
        self.e_bp_3.setText("")
        self.e_bp_3.setObjectName("e_bp_3")
        self.ebpLayout.addWidget(self.e_bp_3)
        self.e_bp_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.e_bp_4.sizePolicy().hasHeightForWidth())
        self.e_bp_4.setSizePolicy(sizePolicy)
        self.e_bp_4.setMinimumSize(QtCore.QSize(32, 32))
        self.e_bp_4.setMaximumSize(QtCore.QSize(32, 32))
        self.e_bp_4.setText("")
        self.e_bp_4.setObjectName("e_bp_4")
        self.ebpLayout.addWidget(self.e_bp_4)
        self.e_bp_5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.e_bp_5.sizePolicy().hasHeightForWidth())
        self.e_bp_5.setSizePolicy(sizePolicy)
        self.e_bp_5.setMinimumSize(QtCore.QSize(32, 32))
        self.e_bp_5.setMaximumSize(QtCore.QSize(32, 32))
        self.e_bp_5.setText("")
        self.e_bp_5.setObjectName("e_bp_5")
        self.ebpLayout.addWidget(self.e_bp_5)
        self.bpLayout.addLayout(self.ebpLayout)
        self.verticalLayout.addLayout(self.bpLayout)
        self.resLayout = QtWidgets.QHBoxLayout()
        self.resLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.resLayout.setObjectName("resLayout")
        self.resEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.resEdit.setObjectName("resEdit")
        self.resLayout.addWidget(self.resEdit)
        self.verticalLayout.addLayout(self.resLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

