# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'select.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(976, 414)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.strLayout = QtWidgets.QVBoxLayout()
        self.strLayout.setObjectName("strLayout")
        self.strLayout_1 = QtWidgets.QHBoxLayout()
        self.strLayout_1.setObjectName("strLayout_1")
        self.elder_titan_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.elder_titan_Btn.sizePolicy().hasHeightForWidth())
        self.elder_titan_Btn.setSizePolicy(sizePolicy)
        self.elder_titan_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.elder_titan_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.elder_titan_Btn.setObjectName("elder_titan_Btn")
        self.strLayout_1.addWidget(self.elder_titan_Btn)
        self.undying_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.undying_Btn.sizePolicy().hasHeightForWidth())
        self.undying_Btn.setSizePolicy(sizePolicy)
        self.undying_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.undying_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.undying_Btn.setObjectName("undying_Btn")
        self.strLayout_1.addWidget(self.undying_Btn)
        self.abaddon_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.abaddon_Btn.sizePolicy().hasHeightForWidth())
        self.abaddon_Btn.setSizePolicy(sizePolicy)
        self.abaddon_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.abaddon_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.abaddon_Btn.setObjectName("abaddon_Btn")
        self.strLayout_1.addWidget(self.abaddon_Btn)
        self.shredder_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shredder_Btn.sizePolicy().hasHeightForWidth())
        self.shredder_Btn.setSizePolicy(sizePolicy)
        self.shredder_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.shredder_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.shredder_Btn.setObjectName("shredder_Btn")
        self.strLayout_1.addWidget(self.shredder_Btn)
        self.omniknight_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.omniknight_Btn.sizePolicy().hasHeightForWidth())
        self.omniknight_Btn.setSizePolicy(sizePolicy)
        self.omniknight_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.omniknight_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.omniknight_Btn.setObjectName("omniknight_Btn")
        self.strLayout_1.addWidget(self.omniknight_Btn)
        self.beastmaster_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.beastmaster_Btn.sizePolicy().hasHeightForWidth())
        self.beastmaster_Btn.setSizePolicy(sizePolicy)
        self.beastmaster_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.beastmaster_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.beastmaster_Btn.setObjectName("beastmaster_Btn")
        self.strLayout_1.addWidget(self.beastmaster_Btn)
        self.legion_commander_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.legion_commander_Btn.sizePolicy().hasHeightForWidth())
        self.legion_commander_Btn.setSizePolicy(sizePolicy)
        self.legion_commander_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.legion_commander_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.legion_commander_Btn.setObjectName("legion_commander_Btn")
        self.strLayout_1.addWidget(self.legion_commander_Btn)
        self.skeleton_king_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skeleton_king_Btn.sizePolicy().hasHeightForWidth())
        self.skeleton_king_Btn.setSizePolicy(sizePolicy)
        self.skeleton_king_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.skeleton_king_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.skeleton_king_Btn.setObjectName("skeleton_king_Btn")
        self.strLayout_1.addWidget(self.skeleton_king_Btn)
        self.phoenix_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phoenix_Btn.sizePolicy().hasHeightForWidth())
        self.phoenix_Btn.setSizePolicy(sizePolicy)
        self.phoenix_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.phoenix_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.phoenix_Btn.setObjectName("phoenix_Btn")
        self.strLayout_1.addWidget(self.phoenix_Btn)
        self.centaur_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centaur_Btn.sizePolicy().hasHeightForWidth())
        self.centaur_Btn.setSizePolicy(sizePolicy)
        self.centaur_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.centaur_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.centaur_Btn.setObjectName("centaur_Btn")
        self.strLayout_1.addWidget(self.centaur_Btn)
        self.rattletrap_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rattletrap_Btn.sizePolicy().hasHeightForWidth())
        self.rattletrap_Btn.setSizePolicy(sizePolicy)
        self.rattletrap_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.rattletrap_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.rattletrap_Btn.setObjectName("rattletrap_Btn")
        self.strLayout_1.addWidget(self.rattletrap_Btn)
        self.huskar_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.huskar_Btn.sizePolicy().hasHeightForWidth())
        self.huskar_Btn.setSizePolicy(sizePolicy)
        self.huskar_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.huskar_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.huskar_Btn.setObjectName("huskar_Btn")
        self.strLayout_1.addWidget(self.huskar_Btn)
        self.life_stealer_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.life_stealer_Btn.sizePolicy().hasHeightForWidth())
        self.life_stealer_Btn.setSizePolicy(sizePolicy)
        self.life_stealer_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.life_stealer_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.life_stealer_Btn.setObjectName("life_stealer_Btn")
        self.strLayout_1.addWidget(self.life_stealer_Btn)
        self.earth_spirit_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.earth_spirit_Btn.sizePolicy().hasHeightForWidth())
        self.earth_spirit_Btn.setSizePolicy(sizePolicy)
        self.earth_spirit_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.earth_spirit_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.earth_spirit_Btn.setObjectName("earth_spirit_Btn")
        self.strLayout_1.addWidget(self.earth_spirit_Btn)
        self.abyssal_underlord_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.abyssal_underlord_Btn.sizePolicy().hasHeightForWidth())
        self.abyssal_underlord_Btn.setSizePolicy(sizePolicy)
        self.abyssal_underlord_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.abyssal_underlord_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.abyssal_underlord_Btn.setObjectName("abyssal_underlord_Btn")
        self.strLayout_1.addWidget(self.abyssal_underlord_Btn)
        self.tiny_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tiny_Btn.sizePolicy().hasHeightForWidth())
        self.tiny_Btn.setSizePolicy(sizePolicy)
        self.tiny_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.tiny_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.tiny_Btn.setObjectName("tiny_Btn")
        self.strLayout_1.addWidget(self.tiny_Btn)
        self.tusk_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tusk_Btn.sizePolicy().hasHeightForWidth())
        self.tusk_Btn.setSizePolicy(sizePolicy)
        self.tusk_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.tusk_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.tusk_Btn.setObjectName("tusk_Btn")
        self.strLayout_1.addWidget(self.tusk_Btn)
        self.pudge_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pudge_Btn.sizePolicy().hasHeightForWidth())
        self.pudge_Btn.setSizePolicy(sizePolicy)
        self.pudge_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.pudge_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.pudge_Btn.setObjectName("pudge_Btn")
        self.strLayout_1.addWidget(self.pudge_Btn)
        self.earthshaker_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.earthshaker_Btn.sizePolicy().hasHeightForWidth())
        self.earthshaker_Btn.setSizePolicy(sizePolicy)
        self.earthshaker_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.earthshaker_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.earthshaker_Btn.setObjectName("earthshaker_Btn")
        self.strLayout_1.addWidget(self.earthshaker_Btn)
        self.axe_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.axe_Btn.sizePolicy().hasHeightForWidth())
        self.axe_Btn.setSizePolicy(sizePolicy)
        self.axe_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.axe_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.axe_Btn.setObjectName("axe_Btn")
        self.strLayout_1.addWidget(self.axe_Btn)
        self.slardar_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slardar_Btn.sizePolicy().hasHeightForWidth())
        self.slardar_Btn.setSizePolicy(sizePolicy)
        self.slardar_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.slardar_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.slardar_Btn.setObjectName("slardar_Btn")
        self.strLayout_1.addWidget(self.slardar_Btn)
        self.strLayout.addLayout(self.strLayout_1)
        self.strLayout_2 = QtWidgets.QHBoxLayout()
        self.strLayout_2.setObjectName("strLayout_2")
        self.sven_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sven_Btn.sizePolicy().hasHeightForWidth())
        self.sven_Btn.setSizePolicy(sizePolicy)
        self.sven_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.sven_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.sven_Btn.setObjectName("sven_Btn")
        self.strLayout_2.addWidget(self.sven_Btn)
        self.kunkka_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kunkka_Btn.sizePolicy().hasHeightForWidth())
        self.kunkka_Btn.setSizePolicy(sizePolicy)
        self.kunkka_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.kunkka_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.kunkka_Btn.setObjectName("kunkka_Btn")
        self.strLayout_2.addWidget(self.kunkka_Btn)
        self.night_stalker_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.night_stalker_Btn.sizePolicy().hasHeightForWidth())
        self.night_stalker_Btn.setSizePolicy(sizePolicy)
        self.night_stalker_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.night_stalker_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.night_stalker_Btn.setObjectName("night_stalker_Btn")
        self.strLayout_2.addWidget(self.night_stalker_Btn)
        self.doom_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doom_Btn.sizePolicy().hasHeightForWidth())
        self.doom_Btn.setSizePolicy(sizePolicy)
        self.doom_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.doom_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.doom_Btn.setObjectName("doom_Btn")
        self.strLayout_2.addWidget(self.doom_Btn)
        self.treant_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treant_Btn.sizePolicy().hasHeightForWidth())
        self.treant_Btn.setSizePolicy(sizePolicy)
        self.treant_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.treant_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.treant_Btn.setObjectName("treant_Btn")
        self.strLayout_2.addWidget(self.treant_Btn)
        self.sand_king_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sand_king_Btn.sizePolicy().hasHeightForWidth())
        self.sand_king_Btn.setSizePolicy(sizePolicy)
        self.sand_king_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.sand_king_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.sand_king_Btn.setObjectName("sand_king_Btn")
        self.strLayout_2.addWidget(self.sand_king_Btn)
        self.chaos_knight_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chaos_knight_Btn.sizePolicy().hasHeightForWidth())
        self.chaos_knight_Btn.setSizePolicy(sizePolicy)
        self.chaos_knight_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.chaos_knight_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.chaos_knight_Btn.setObjectName("chaos_knight_Btn")
        self.strLayout_2.addWidget(self.chaos_knight_Btn)
        self.tidehunter_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tidehunter_Btn.sizePolicy().hasHeightForWidth())
        self.tidehunter_Btn.setSizePolicy(sizePolicy)
        self.tidehunter_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.tidehunter_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.tidehunter_Btn.setObjectName("tidehunter_Btn")
        self.strLayout_2.addWidget(self.tidehunter_Btn)
        self.alchemist_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alchemist_Btn.sizePolicy().hasHeightForWidth())
        self.alchemist_Btn.setSizePolicy(sizePolicy)
        self.alchemist_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.alchemist_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.alchemist_Btn.setObjectName("alchemist_Btn")
        self.strLayout_2.addWidget(self.alchemist_Btn)
        self.lycan_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lycan_Btn.sizePolicy().hasHeightForWidth())
        self.lycan_Btn.setSizePolicy(sizePolicy)
        self.lycan_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.lycan_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.lycan_Btn.setObjectName("lycan_Btn")
        self.strLayout_2.addWidget(self.lycan_Btn)
        self.wisp_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wisp_Btn.sizePolicy().hasHeightForWidth())
        self.wisp_Btn.setSizePolicy(sizePolicy)
        self.wisp_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.wisp_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.wisp_Btn.setObjectName("wisp_Btn")
        self.strLayout_2.addWidget(self.wisp_Btn)
        self.spirit_breaker_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spirit_breaker_Btn.sizePolicy().hasHeightForWidth())
        self.spirit_breaker_Btn.setSizePolicy(sizePolicy)
        self.spirit_breaker_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.spirit_breaker_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.spirit_breaker_Btn.setObjectName("spirit_breaker_Btn")
        self.strLayout_2.addWidget(self.spirit_breaker_Btn)
        self.brewmaster_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brewmaster_Btn.sizePolicy().hasHeightForWidth())
        self.brewmaster_Btn.setSizePolicy(sizePolicy)
        self.brewmaster_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.brewmaster_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.brewmaster_Btn.setObjectName("brewmaster_Btn")
        self.strLayout_2.addWidget(self.brewmaster_Btn)
        self.bristleback_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bristleback_Btn.sizePolicy().hasHeightForWidth())
        self.bristleback_Btn.setSizePolicy(sizePolicy)
        self.bristleback_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.bristleback_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.bristleback_Btn.setObjectName("bristleback_Btn")
        self.strLayout_2.addWidget(self.bristleback_Btn)
        self.magnataur_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.magnataur_Btn.sizePolicy().hasHeightForWidth())
        self.magnataur_Btn.setSizePolicy(sizePolicy)
        self.magnataur_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.magnataur_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.magnataur_Btn.setObjectName("magnataur_Btn")
        self.strLayout_2.addWidget(self.magnataur_Btn)
        self.dragon_knight_Btnm = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dragon_knight_Btnm.sizePolicy().hasHeightForWidth())
        self.dragon_knight_Btnm.setSizePolicy(sizePolicy)
        self.dragon_knight_Btnm.setMinimumSize(QtCore.QSize(32, 32))
        self.dragon_knight_Btnm.setMaximumSize(QtCore.QSize(32, 32))
        self.dragon_knight_Btnm.setObjectName("dragon_knight_Btnm")
        self.strLayout_2.addWidget(self.dragon_knight_Btnm)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.strLayout_2.addItem(spacerItem)
        self.strLayout.addLayout(self.strLayout_2)
        self.verticalLayout.addLayout(self.strLayout)
        self.agiLayout = QtWidgets.QVBoxLayout()
        self.agiLayout.setObjectName("agiLayout")
        self.agiLayout_1 = QtWidgets.QHBoxLayout()
        self.agiLayout_1.setObjectName("agiLayout_1")
        self.juggernaut_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.juggernaut_Btn.sizePolicy().hasHeightForWidth())
        self.juggernaut_Btn.setSizePolicy(sizePolicy)
        self.juggernaut_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.juggernaut_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.juggernaut_Btn.setObjectName("juggernaut_Btn")
        self.agiLayout_1.addWidget(self.juggernaut_Btn)
        self.clinkz_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clinkz_Btn.sizePolicy().hasHeightForWidth())
        self.clinkz_Btn.setSizePolicy(sizePolicy)
        self.clinkz_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.clinkz_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.clinkz_Btn.setObjectName("clinkz_Btn")
        self.agiLayout_1.addWidget(self.clinkz_Btn)
        self.viper_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viper_Btn.sizePolicy().hasHeightForWidth())
        self.viper_Btn.setSizePolicy(sizePolicy)
        self.viper_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.viper_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.viper_Btn.setObjectName("viper_Btn")
        self.agiLayout_1.addWidget(self.viper_Btn)
        self.razor_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.razor_Btn.sizePolicy().hasHeightForWidth())
        self.razor_Btn.setSizePolicy(sizePolicy)
        self.razor_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.razor_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.razor_Btn.setObjectName("razor_Btn")
        self.agiLayout_1.addWidget(self.razor_Btn)
        self.venomancer_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.venomancer_Btn.sizePolicy().hasHeightForWidth())
        self.venomancer_Btn.setSizePolicy(sizePolicy)
        self.venomancer_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.venomancer_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.venomancer_Btn.setObjectName("venomancer_Btn")
        self.agiLayout_1.addWidget(self.venomancer_Btn)
        self.rikimaru_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rikimaru_Btn.sizePolicy().hasHeightForWidth())
        self.rikimaru_Btn.setSizePolicy(sizePolicy)
        self.rikimaru_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.rikimaru_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.rikimaru_Btn.setObjectName("rikimaru_Btn")
        self.agiLayout_1.addWidget(self.rikimaru_Btn)
        self.drow_ranger_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drow_ranger_Btn.sizePolicy().hasHeightForWidth())
        self.drow_ranger_Btn.setSizePolicy(sizePolicy)
        self.drow_ranger_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.drow_ranger_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.drow_ranger_Btn.setObjectName("drow_ranger_Btn")
        self.agiLayout_1.addWidget(self.drow_ranger_Btn)
        self.morphling_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.morphling_Btn.sizePolicy().hasHeightForWidth())
        self.morphling_Btn.setSizePolicy(sizePolicy)
        self.morphling_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.morphling_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.morphling_Btn.setObjectName("morphling_Btn")
        self.agiLayout_1.addWidget(self.morphling_Btn)
        self.nyx_assassin_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nyx_assassin_Btn.sizePolicy().hasHeightForWidth())
        self.nyx_assassin_Btn.setSizePolicy(sizePolicy)
        self.nyx_assassin_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.nyx_assassin_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.nyx_assassin_Btn.setObjectName("nyx_assassin_Btn")
        self.agiLayout_1.addWidget(self.nyx_assassin_Btn)
        self.bloodseeker_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bloodseeker_Btn.sizePolicy().hasHeightForWidth())
        self.bloodseeker_Btn.setSizePolicy(sizePolicy)
        self.bloodseeker_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.bloodseeker_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.bloodseeker_Btn.setObjectName("bloodseeker_Btn")
        self.agiLayout_1.addWidget(self.bloodseeker_Btn)
        self.templar_assassin_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.templar_assassin_Btn.sizePolicy().hasHeightForWidth())
        self.templar_assassin_Btn.setSizePolicy(sizePolicy)
        self.templar_assassin_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.templar_assassin_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.templar_assassin_Btn.setObjectName("templar_assassin_Btn")
        self.agiLayout_1.addWidget(self.templar_assassin_Btn)
        self.vengefulspirit_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vengefulspirit_Btn.sizePolicy().hasHeightForWidth())
        self.vengefulspirit_Btn.setSizePolicy(sizePolicy)
        self.vengefulspirit_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.vengefulspirit_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.vengefulspirit_Btn.setObjectName("vengefulspirit_Btn")
        self.agiLayout_1.addWidget(self.vengefulspirit_Btn)
        self.arc_warden_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arc_warden_Btn.sizePolicy().hasHeightForWidth())
        self.arc_warden_Btn.setSizePolicy(sizePolicy)
        self.arc_warden_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.arc_warden_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.arc_warden_Btn.setObjectName("arc_warden_Btn")
        self.agiLayout_1.addWidget(self.arc_warden_Btn)
        self.naga_siren_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.naga_siren_Btn.sizePolicy().hasHeightForWidth())
        self.naga_siren_Btn.setSizePolicy(sizePolicy)
        self.naga_siren_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.naga_siren_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.naga_siren_Btn.setObjectName("naga_siren_Btn")
        self.agiLayout_1.addWidget(self.naga_siren_Btn)
        self.troll_warlord_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.troll_warlord_Btn.sizePolicy().hasHeightForWidth())
        self.troll_warlord_Btn.setSizePolicy(sizePolicy)
        self.troll_warlord_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.troll_warlord_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.troll_warlord_Btn.setObjectName("troll_warlord_Btn")
        self.agiLayout_1.addWidget(self.troll_warlord_Btn)
        self.phantom_assassin_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phantom_assassin_Btn.sizePolicy().hasHeightForWidth())
        self.phantom_assassin_Btn.setSizePolicy(sizePolicy)
        self.phantom_assassin_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.phantom_assassin_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.phantom_assassin_Btn.setObjectName("phantom_assassin_Btn")
        self.agiLayout_1.addWidget(self.phantom_assassin_Btn)
        self.phantom_lancer_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phantom_lancer_Btn.sizePolicy().hasHeightForWidth())
        self.phantom_lancer_Btn.setSizePolicy(sizePolicy)
        self.phantom_lancer_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.phantom_lancer_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.phantom_lancer_Btn.setObjectName("phantom_lancer_Btn")
        self.agiLayout_1.addWidget(self.phantom_lancer_Btn)
        self.spectre_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spectre_Btn.sizePolicy().hasHeightForWidth())
        self.spectre_Btn.setSizePolicy(sizePolicy)
        self.spectre_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.spectre_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.spectre_Btn.setObjectName("spectre_Btn")
        self.agiLayout_1.addWidget(self.spectre_Btn)
        self.nevermore_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nevermore_Btn.sizePolicy().hasHeightForWidth())
        self.nevermore_Btn.setSizePolicy(sizePolicy)
        self.nevermore_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.nevermore_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.nevermore_Btn.setObjectName("nevermore_Btn")
        self.agiLayout_1.addWidget(self.nevermore_Btn)
        self.lone_druid_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lone_druid_Btn.sizePolicy().hasHeightForWidth())
        self.lone_druid_Btn.setSizePolicy(sizePolicy)
        self.lone_druid_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.lone_druid_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.lone_druid_Btn.setObjectName("lone_druid_Btn")
        self.agiLayout_1.addWidget(self.lone_druid_Btn)
        self.terrorblade_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.terrorblade_Btn.sizePolicy().hasHeightForWidth())
        self.terrorblade_Btn.setSizePolicy(sizePolicy)
        self.terrorblade_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.terrorblade_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.terrorblade_Btn.setObjectName("terrorblade_Btn")
        self.agiLayout_1.addWidget(self.terrorblade_Btn)
        self.agiLayout.addLayout(self.agiLayout_1)
        self.agiLayout_2 = QtWidgets.QHBoxLayout()
        self.agiLayout_2.setObjectName("agiLayout_2")
        self.antimage_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.antimage_Btn.sizePolicy().hasHeightForWidth())
        self.antimage_Btn.setSizePolicy(sizePolicy)
        self.antimage_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.antimage_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.antimage_Btn.setObjectName("antimage_Btn")
        self.agiLayout_2.addWidget(self.antimage_Btn)
        self.slark_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slark_Btn.sizePolicy().hasHeightForWidth())
        self.slark_Btn.setSizePolicy(sizePolicy)
        self.slark_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.slark_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.slark_Btn.setObjectName("slark_Btn")
        self.agiLayout_2.addWidget(self.slark_Btn)
        self.ember_spirit_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ember_spirit_Btn.sizePolicy().hasHeightForWidth())
        self.ember_spirit_Btn.setSizePolicy(sizePolicy)
        self.ember_spirit_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.ember_spirit_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.ember_spirit_Btn.setObjectName("ember_spirit_Btn")
        self.agiLayout_2.addWidget(self.ember_spirit_Btn)
        self.ursa_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ursa_Btn.sizePolicy().hasHeightForWidth())
        self.ursa_Btn.setSizePolicy(sizePolicy)
        self.ursa_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.ursa_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.ursa_Btn.setObjectName("ursa_Btn")
        self.agiLayout_2.addWidget(self.ursa_Btn)
        self.sniper_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sniper_Btn.sizePolicy().hasHeightForWidth())
        self.sniper_Btn.setSizePolicy(sizePolicy)
        self.sniper_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.sniper_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.sniper_Btn.setObjectName("sniper_Btn")
        self.agiLayout_2.addWidget(self.sniper_Btn)
        self.gyrocopter_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gyrocopter_Btn.sizePolicy().hasHeightForWidth())
        self.gyrocopter_Btn.setSizePolicy(sizePolicy)
        self.gyrocopter_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.gyrocopter_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.gyrocopter_Btn.setObjectName("gyrocopter_Btn")
        self.agiLayout_2.addWidget(self.gyrocopter_Btn)
        self.pangolier_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pangolier_Btn.sizePolicy().hasHeightForWidth())
        self.pangolier_Btn.setSizePolicy(sizePolicy)
        self.pangolier_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.pangolier_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.pangolier_Btn.setObjectName("pangolier_Btn")
        self.agiLayout_2.addWidget(self.pangolier_Btn)
        self.mirana_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mirana_Btn.sizePolicy().hasHeightForWidth())
        self.mirana_Btn.setSizePolicy(sizePolicy)
        self.mirana_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.mirana_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.mirana_Btn.setObjectName("mirana_Btn")
        self.agiLayout_2.addWidget(self.mirana_Btn)
        self.meepo_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meepo_Btn.sizePolicy().hasHeightForWidth())
        self.meepo_Btn.setSizePolicy(sizePolicy)
        self.meepo_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.meepo_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.meepo_Btn.setObjectName("meepo_Btn")
        self.agiLayout_2.addWidget(self.meepo_Btn)
        self.weaver_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weaver_Btn.sizePolicy().hasHeightForWidth())
        self.weaver_Btn.setSizePolicy(sizePolicy)
        self.weaver_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.weaver_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.weaver_Btn.setObjectName("weaver_Btn")
        self.agiLayout_2.addWidget(self.weaver_Btn)
        self.medusa_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.medusa_Btn.sizePolicy().hasHeightForWidth())
        self.medusa_Btn.setSizePolicy(sizePolicy)
        self.medusa_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.medusa_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.medusa_Btn.setObjectName("medusa_Btn")
        self.agiLayout_2.addWidget(self.medusa_Btn)
        self.broodmother_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.broodmother_Btn.sizePolicy().hasHeightForWidth())
        self.broodmother_Btn.setSizePolicy(sizePolicy)
        self.broodmother_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.broodmother_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.broodmother_Btn.setObjectName("broodmother_Btn")
        self.agiLayout_2.addWidget(self.broodmother_Btn)
        self.faceless_void_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.faceless_void_Btn.sizePolicy().hasHeightForWidth())
        self.faceless_void_Btn.setSizePolicy(sizePolicy)
        self.faceless_void_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.faceless_void_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.faceless_void_Btn.setObjectName("faceless_void_Btn")
        self.agiLayout_2.addWidget(self.faceless_void_Btn)
        self.bounty_hunter_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bounty_hunter_Btn.sizePolicy().hasHeightForWidth())
        self.bounty_hunter_Btn.setSizePolicy(sizePolicy)
        self.bounty_hunter_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.bounty_hunter_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.bounty_hunter_Btn.setObjectName("bounty_hunter_Btn")
        self.agiLayout_2.addWidget(self.bounty_hunter_Btn)
        self.luna_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.luna_Btn.sizePolicy().hasHeightForWidth())
        self.luna_Btn.setSizePolicy(sizePolicy)
        self.luna_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.luna_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.luna_Btn.setObjectName("luna_Btn")
        self.agiLayout_2.addWidget(self.luna_Btn)
        self.monkey_king_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.monkey_king_Btn.sizePolicy().hasHeightForWidth())
        self.monkey_king_Btn.setSizePolicy(sizePolicy)
        self.monkey_king_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.monkey_king_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.monkey_king_Btn.setObjectName("monkey_king_Btn")
        self.agiLayout_2.addWidget(self.monkey_king_Btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.agiLayout_2.addItem(spacerItem1)
        self.agiLayout.addLayout(self.agiLayout_2)
        self.verticalLayout.addLayout(self.agiLayout)
        self.intLayout = QtWidgets.QVBoxLayout()
        self.intLayout.setObjectName("intLayout")
        self.intLayout_1 = QtWidgets.QHBoxLayout()
        self.intLayout_1.setObjectName("intLayout_1")
        self.tinker_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tinker_Btn.sizePolicy().hasHeightForWidth())
        self.tinker_Btn.setSizePolicy(sizePolicy)
        self.tinker_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.tinker_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.tinker_Btn.setObjectName("tinker_Btn")
        self.intLayout_1.addWidget(self.tinker_Btn)
        self.furion_BTn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.furion_BTn.sizePolicy().hasHeightForWidth())
        self.furion_BTn.setSizePolicy(sizePolicy)
        self.furion_BTn.setMinimumSize(QtCore.QSize(32, 32))
        self.furion_BTn.setMaximumSize(QtCore.QSize(32, 32))
        self.furion_BTn.setObjectName("furion_BTn")
        self.intLayout_1.addWidget(self.furion_BTn)
        self.keeper_of_the_light_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keeper_of_the_light_Btn.sizePolicy().hasHeightForWidth())
        self.keeper_of_the_light_Btn.setSizePolicy(sizePolicy)
        self.keeper_of_the_light_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.keeper_of_the_light_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.keeper_of_the_light_Btn.setObjectName("keeper_of_the_light_Btn")
        self.intLayout_1.addWidget(self.keeper_of_the_light_Btn)
        self.skywrath_mage_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skywrath_mage_Btn.sizePolicy().hasHeightForWidth())
        self.skywrath_mage_Btn.setSizePolicy(sizePolicy)
        self.skywrath_mage_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.skywrath_mage_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.skywrath_mage_Btn.setObjectName("skywrath_mage_Btn")
        self.intLayout_1.addWidget(self.skywrath_mage_Btn)
        self.zuus_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zuus_Btn.sizePolicy().hasHeightForWidth())
        self.zuus_Btn.setSizePolicy(sizePolicy)
        self.zuus_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.zuus_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.zuus_Btn.setObjectName("zuus_Btn")
        self.intLayout_1.addWidget(self.zuus_Btn)
        self.winter_wyvern_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.winter_wyvern_Btn.sizePolicy().hasHeightForWidth())
        self.winter_wyvern_Btn.setSizePolicy(sizePolicy)
        self.winter_wyvern_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.winter_wyvern_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.winter_wyvern_Btn.setObjectName("winter_wyvern_Btn")
        self.intLayout_1.addWidget(self.winter_wyvern_Btn)
        self.techies_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.techies_Btn.sizePolicy().hasHeightForWidth())
        self.techies_Btn.setSizePolicy(sizePolicy)
        self.techies_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.techies_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.techies_Btn.setObjectName("techies_Btn")
        self.intLayout_1.addWidget(self.techies_Btn)
        self.witch_doctor_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.witch_doctor_Btn.sizePolicy().hasHeightForWidth())
        self.witch_doctor_Btn.setSizePolicy(sizePolicy)
        self.witch_doctor_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.witch_doctor_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.witch_doctor_Btn.setObjectName("witch_doctor_Btn")
        self.intLayout_1.addWidget(self.witch_doctor_Btn)
        self.lich_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lich_Btn.sizePolicy().hasHeightForWidth())
        self.lich_Btn.setSizePolicy(sizePolicy)
        self.lich_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.lich_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.lich_Btn.setObjectName("lich_Btn")
        self.intLayout_1.addWidget(self.lich_Btn)
        self.puck_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.puck_Btn.sizePolicy().hasHeightForWidth())
        self.puck_Btn.setSizePolicy(sizePolicy)
        self.puck_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.puck_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.puck_Btn.setObjectName("puck_Btn")
        self.intLayout_1.addWidget(self.puck_Btn)
        self.pugna_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pugna_Btn.sizePolicy().hasHeightForWidth())
        self.pugna_Btn.setSizePolicy(sizePolicy)
        self.pugna_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.pugna_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.pugna_Btn.setObjectName("pugna_Btn")
        self.intLayout_1.addWidget(self.pugna_Btn)
        self.disruptor_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.disruptor_Btn.sizePolicy().hasHeightForWidth())
        self.disruptor_Btn.setSizePolicy(sizePolicy)
        self.disruptor_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.disruptor_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.disruptor_Btn.setObjectName("disruptor_Btn")
        self.intLayout_1.addWidget(self.disruptor_Btn)
        self.dazzle_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dazzle_Btn.sizePolicy().hasHeightForWidth())
        self.dazzle_Btn.setSizePolicy(sizePolicy)
        self.dazzle_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.dazzle_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.dazzle_Btn.setObjectName("dazzle_Btn")
        self.intLayout_1.addWidget(self.dazzle_Btn)
        self.leshrac_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leshrac_Btn.sizePolicy().hasHeightForWidth())
        self.leshrac_Btn.setSizePolicy(sizePolicy)
        self.leshrac_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.leshrac_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.leshrac_Btn.setObjectName("leshrac_Btn")
        self.intLayout_1.addWidget(self.leshrac_Btn)
        self.rubick_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rubick_Btn.sizePolicy().hasHeightForWidth())
        self.rubick_Btn.setSizePolicy(sizePolicy)
        self.rubick_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.rubick_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.rubick_Btn.setObjectName("rubick_Btn")
        self.intLayout_1.addWidget(self.rubick_Btn)
        self.shadow_demon_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shadow_demon_Btn.sizePolicy().hasHeightForWidth())
        self.shadow_demon_Btn.setSizePolicy(sizePolicy)
        self.shadow_demon_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.shadow_demon_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.shadow_demon_Btn.setObjectName("shadow_demon_Btn")
        self.intLayout_1.addWidget(self.shadow_demon_Btn)
        self.shadow_shaman_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shadow_shaman_Btn.sizePolicy().hasHeightForWidth())
        self.shadow_shaman_Btn.setSizePolicy(sizePolicy)
        self.shadow_shaman_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.shadow_shaman_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.shadow_shaman_Btn.setObjectName("shadow_shaman_Btn")
        self.intLayout_1.addWidget(self.shadow_shaman_Btn)
        self.warlock_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.warlock_Btn.sizePolicy().hasHeightForWidth())
        self.warlock_Btn.setSizePolicy(sizePolicy)
        self.warlock_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.warlock_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.warlock_Btn.setObjectName("warlock_Btn")
        self.intLayout_1.addWidget(self.warlock_Btn)
        self.jakiro_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jakiro_Btn.sizePolicy().hasHeightForWidth())
        self.jakiro_Btn.setSizePolicy(sizePolicy)
        self.jakiro_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.jakiro_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.jakiro_Btn.setObjectName("jakiro_Btn")
        self.intLayout_1.addWidget(self.jakiro_Btn)
        self.death_prophet_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.death_prophet_Btn.sizePolicy().hasHeightForWidth())
        self.death_prophet_Btn.setSizePolicy(sizePolicy)
        self.death_prophet_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.death_prophet_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.death_prophet_Btn.setObjectName("death_prophet_Btn")
        self.intLayout_1.addWidget(self.death_prophet_Btn)
        self.obsidian_destroyer_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.obsidian_destroyer_Btn.sizePolicy().hasHeightForWidth())
        self.obsidian_destroyer_Btn.setSizePolicy(sizePolicy)
        self.obsidian_destroyer_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.obsidian_destroyer_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.obsidian_destroyer_Btn.setObjectName("obsidian_destroyer_Btn")
        self.intLayout_1.addWidget(self.obsidian_destroyer_Btn)
        self.intLayout.addLayout(self.intLayout_1)
        self.intLayout_2 = QtWidgets.QHBoxLayout()
        self.intLayout_2.setObjectName("intLayout_2")
        self.crystal_maiden_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.crystal_maiden_Btn.sizePolicy().hasHeightForWidth())
        self.crystal_maiden_Btn.setSizePolicy(sizePolicy)
        self.crystal_maiden_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.crystal_maiden_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.crystal_maiden_Btn.setObjectName("crystal_maiden_Btn")
        self.intLayout_2.addWidget(self.crystal_maiden_Btn)
        self.silencer_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.silencer_Btn.sizePolicy().hasHeightForWidth())
        self.silencer_Btn.setSizePolicy(sizePolicy)
        self.silencer_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.silencer_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.silencer_Btn.setObjectName("silencer_Btn")
        self.intLayout_2.addWidget(self.silencer_Btn)
        self.queenofpain_btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.queenofpain_btn.sizePolicy().hasHeightForWidth())
        self.queenofpain_btn.setSizePolicy(sizePolicy)
        self.queenofpain_btn.setMinimumSize(QtCore.QSize(32, 32))
        self.queenofpain_btn.setMaximumSize(QtCore.QSize(32, 32))
        self.queenofpain_btn.setObjectName("queenofpain_btn")
        self.intLayout_2.addWidget(self.queenofpain_btn)
        self.necrolyte_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.necrolyte_Btn.sizePolicy().hasHeightForWidth())
        self.necrolyte_Btn.setSizePolicy(sizePolicy)
        self.necrolyte_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.necrolyte_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.necrolyte_Btn.setObjectName("necrolyte_Btn")
        self.intLayout_2.addWidget(self.necrolyte_Btn)
        self.invoker_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.invoker_Btn.sizePolicy().hasHeightForWidth())
        self.invoker_Btn.setSizePolicy(sizePolicy)
        self.invoker_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.invoker_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.invoker_Btn.setObjectName("invoker_Btn")
        self.intLayout_2.addWidget(self.invoker_Btn)
        self.oracle_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oracle_Btn.sizePolicy().hasHeightForWidth())
        self.oracle_Btn.setSizePolicy(sizePolicy)
        self.oracle_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.oracle_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.oracle_Btn.setObjectName("oracle_Btn")
        self.intLayout_2.addWidget(self.oracle_Btn)
        self.bane_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bane_Btn.sizePolicy().hasHeightForWidth())
        self.bane_Btn.setSizePolicy(sizePolicy)
        self.bane_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.bane_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.bane_Btn.setObjectName("bane_Btn")
        self.intLayout_2.addWidget(self.bane_Btn)
        self.visage_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visage_Btn.sizePolicy().hasHeightForWidth())
        self.visage_Btn.setSizePolicy(sizePolicy)
        self.visage_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.visage_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.visage_Btn.setObjectName("visage_Btn")
        self.intLayout_2.addWidget(self.visage_Btn)
        self.lina_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lina_Btn.sizePolicy().hasHeightForWidth())
        self.lina_Btn.setSizePolicy(sizePolicy)
        self.lina_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.lina_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.lina_Btn.setObjectName("lina_Btn")
        self.intLayout_2.addWidget(self.lina_Btn)
        self.lion_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lion_Btn.sizePolicy().hasHeightForWidth())
        self.lion_Btn.setSizePolicy(sizePolicy)
        self.lion_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.lion_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.lion_Btn.setObjectName("lion_Btn")
        self.intLayout_2.addWidget(self.lion_Btn)
        self.batrider_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.batrider_Btn.sizePolicy().hasHeightForWidth())
        self.batrider_Btn.setSizePolicy(sizePolicy)
        self.batrider_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.batrider_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.batrider_Btn.setObjectName("batrider_Btn")
        self.intLayout_2.addWidget(self.batrider_Btn)
        self.enigma_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.enigma_Btn.sizePolicy().hasHeightForWidth())
        self.enigma_Btn.setSizePolicy(sizePolicy)
        self.enigma_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.enigma_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.enigma_Btn.setObjectName("enigma_Btn")
        self.intLayout_2.addWidget(self.enigma_Btn)
        self.ancient_apparition_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ancient_apparition_Btn.sizePolicy().hasHeightForWidth())
        self.ancient_apparition_Btn.setSizePolicy(sizePolicy)
        self.ancient_apparition_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.ancient_apparition_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.ancient_apparition_Btn.setObjectName("ancient_apparition_Btn")
        self.intLayout_2.addWidget(self.ancient_apparition_Btn)
        self.dark_willow_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dark_willow_Btn.sizePolicy().hasHeightForWidth())
        self.dark_willow_Btn.setSizePolicy(sizePolicy)
        self.dark_willow_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.dark_willow_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.dark_willow_Btn.setObjectName("dark_willow_Btn")
        self.intLayout_2.addWidget(self.dark_willow_Btn)
        self.chen_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chen_Btn.sizePolicy().hasHeightForWidth())
        self.chen_Btn.setSizePolicy(sizePolicy)
        self.chen_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.chen_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.chen_Btn.setObjectName("chen_Btn")
        self.intLayout_2.addWidget(self.chen_Btn)
        self.storm_spirit_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.storm_spirit_Btn.sizePolicy().hasHeightForWidth())
        self.storm_spirit_Btn.setSizePolicy(sizePolicy)
        self.storm_spirit_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.storm_spirit_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.storm_spirit_Btn.setObjectName("storm_spirit_Btn")
        self.intLayout_2.addWidget(self.storm_spirit_Btn)
        self.windrunner_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.windrunner_Btn.sizePolicy().hasHeightForWidth())
        self.windrunner_Btn.setSizePolicy(sizePolicy)
        self.windrunner_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.windrunner_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.windrunner_Btn.setObjectName("windrunner_Btn")
        self.intLayout_2.addWidget(self.windrunner_Btn)
        self.ogre_magi_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ogre_magi_Btn.sizePolicy().hasHeightForWidth())
        self.ogre_magi_Btn.setSizePolicy(sizePolicy)
        self.ogre_magi_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.ogre_magi_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.ogre_magi_Btn.setObjectName("ogre_magi_Btn")
        self.intLayout_2.addWidget(self.ogre_magi_Btn)
        self.enchantress_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.enchantress_Btn.sizePolicy().hasHeightForWidth())
        self.enchantress_Btn.setSizePolicy(sizePolicy)
        self.enchantress_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.enchantress_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.enchantress_Btn.setObjectName("enchantress_Btn")
        self.intLayout_2.addWidget(self.enchantress_Btn)
        self.dark_seer_Btn = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dark_seer_Btn.sizePolicy().hasHeightForWidth())
        self.dark_seer_Btn.setSizePolicy(sizePolicy)
        self.dark_seer_Btn.setMinimumSize(QtCore.QSize(32, 32))
        self.dark_seer_Btn.setMaximumSize(QtCore.QSize(32, 32))
        self.dark_seer_Btn.setObjectName("dark_seer_Btn")
        self.intLayout_2.addWidget(self.dark_seer_Btn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.intLayout_2.addItem(spacerItem2)
        self.intLayout.addLayout(self.intLayout_2)
        self.verticalLayout.addLayout(self.intLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.elder_titan_Btn.setText(_translate("Form", "elder_titan"))
        self.undying_Btn.setText(_translate("Form", "undying"))
        self.abaddon_Btn.setText(_translate("Form", "abaddon"))
        self.shredder_Btn.setText(_translate("Form", "shredder"))
        self.omniknight_Btn.setText(_translate("Form", "omniknight"))
        self.beastmaster_Btn.setText(_translate("Form", "beastmaster"))
        self.legion_commander_Btn.setText(_translate("Form", "legion_commander"))
        self.skeleton_king_Btn.setText(_translate("Form", "skeleton_king"))
        self.phoenix_Btn.setText(_translate("Form", "phoenix"))
        self.centaur_Btn.setText(_translate("Form", "centaur"))
        self.rattletrap_Btn.setText(_translate("Form", "rattletrap"))
        self.huskar_Btn.setText(_translate("Form", "huskar"))
        self.life_stealer_Btn.setText(_translate("Form", "life_stealer"))
        self.earth_spirit_Btn.setText(_translate("Form", "earth_spirit"))
        self.abyssal_underlord_Btn.setText(_translate("Form", "abyssal_underlord"))
        self.tiny_Btn.setText(_translate("Form", "tiny"))
        self.tusk_Btn.setText(_translate("Form", "tusk"))
        self.pudge_Btn.setText(_translate("Form", "pudge"))
        self.earthshaker_Btn.setText(_translate("Form", "earthshaker"))
        self.axe_Btn.setText(_translate("Form", "axe"))
        self.slardar_Btn.setText(_translate("Form", "slardar"))
        self.sven_Btn.setText(_translate("Form", "sven"))
        self.kunkka_Btn.setText(_translate("Form", "kunkka"))
        self.night_stalker_Btn.setText(_translate("Form", "night_stalker"))
        self.doom_Btn.setText(_translate("Form", "doom"))
        self.treant_Btn.setText(_translate("Form", "treant"))
        self.sand_king_Btn.setText(_translate("Form", "sand_king"))
        self.chaos_knight_Btn.setText(_translate("Form", "chaos_knight"))
        self.tidehunter_Btn.setText(_translate("Form", "tidehunter"))
        self.alchemist_Btn.setText(_translate("Form", "alchemist"))
        self.lycan_Btn.setText(_translate("Form", "lycan"))
        self.wisp_Btn.setText(_translate("Form", "wisp"))
        self.spirit_breaker_Btn.setText(_translate("Form", "spirit_breaker"))
        self.brewmaster_Btn.setText(_translate("Form", "brewmaster"))
        self.bristleback_Btn.setText(_translate("Form", "bristleback"))
        self.magnataur_Btn.setText(_translate("Form", "magnataur"))
        self.dragon_knight_Btnm.setText(_translate("Form", "dragon_knight"))
        self.juggernaut_Btn.setText(_translate("Form", "juggernaut"))
        self.clinkz_Btn.setText(_translate("Form", "clinkz"))
        self.viper_Btn.setText(_translate("Form", "viper"))
        self.razor_Btn.setText(_translate("Form", "razor"))
        self.venomancer_Btn.setText(_translate("Form", "venomancer"))
        self.rikimaru_Btn.setText(_translate("Form", "rikimaru"))
        self.drow_ranger_Btn.setText(_translate("Form", "drow_ranger"))
        self.morphling_Btn.setText(_translate("Form", "morphling"))
        self.nyx_assassin_Btn.setText(_translate("Form", "nyx_assassin"))
        self.bloodseeker_Btn.setText(_translate("Form", "bloodseeker"))
        self.templar_assassin_Btn.setText(_translate("Form", "templar_assassin"))
        self.vengefulspirit_Btn.setText(_translate("Form", "vengefulspirit"))
        self.arc_warden_Btn.setText(_translate("Form", "arc_warden"))
        self.naga_siren_Btn.setText(_translate("Form", "naga_siren"))
        self.troll_warlord_Btn.setText(_translate("Form", "troll_warlord"))
        self.phantom_assassin_Btn.setText(_translate("Form", "phantom_assassin"))
        self.phantom_lancer_Btn.setText(_translate("Form", "phantom_lancer"))
        self.spectre_Btn.setText(_translate("Form", "spectre"))
        self.nevermore_Btn.setText(_translate("Form", "nevermore"))
        self.lone_druid_Btn.setText(_translate("Form", "lone_druid"))
        self.terrorblade_Btn.setText(_translate("Form", "terrorblade"))
        self.antimage_Btn.setText(_translate("Form", "antimage"))
        self.slark_Btn.setText(_translate("Form", "slark"))
        self.ember_spirit_Btn.setText(_translate("Form", "ember_spirit"))
        self.ursa_Btn.setText(_translate("Form", "ursa"))
        self.sniper_Btn.setText(_translate("Form", "sniper"))
        self.gyrocopter_Btn.setText(_translate("Form", "gyrocopter"))
        self.pangolier_Btn.setText(_translate("Form", "pangolier"))
        self.mirana_Btn.setText(_translate("Form", "mirana"))
        self.meepo_Btn.setText(_translate("Form", "meepo"))
        self.weaver_Btn.setText(_translate("Form", "weaver"))
        self.medusa_Btn.setText(_translate("Form", "medusa"))
        self.broodmother_Btn.setText(_translate("Form", "broodmother"))
        self.faceless_void_Btn.setText(_translate("Form", "faceless_void"))
        self.bounty_hunter_Btn.setText(_translate("Form", "bounty_hunter"))
        self.luna_Btn.setText(_translate("Form", "luna"))
        self.monkey_king_Btn.setText(_translate("Form", "monkey_king"))
        self.tinker_Btn.setText(_translate("Form", "tinker"))
        self.furion_BTn.setText(_translate("Form", "furion"))
        self.keeper_of_the_light_Btn.setText(_translate("Form", "keeper_of_the_light"))
        self.skywrath_mage_Btn.setText(_translate("Form", "skywrath_mage"))
        self.zuus_Btn.setText(_translate("Form", "zuus"))
        self.winter_wyvern_Btn.setText(_translate("Form", "winter_wyvern"))
        self.techies_Btn.setText(_translate("Form", "techies"))
        self.witch_doctor_Btn.setText(_translate("Form", "witch_doctor"))
        self.lich_Btn.setText(_translate("Form", "lich"))
        self.puck_Btn.setText(_translate("Form", "puck"))
        self.pugna_Btn.setText(_translate("Form", "pugna"))
        self.disruptor_Btn.setText(_translate("Form", "disruptor"))
        self.dazzle_Btn.setText(_translate("Form", "dazzle"))
        self.leshrac_Btn.setText(_translate("Form", "leshrac"))
        self.rubick_Btn.setText(_translate("Form", "rubick"))
        self.shadow_demon_Btn.setText(_translate("Form", "shadow_demon"))
        self.shadow_shaman_Btn.setText(_translate("Form", "shadow_shaman"))
        self.warlock_Btn.setText(_translate("Form", "warlock"))
        self.jakiro_Btn.setText(_translate("Form", "jakiro"))
        self.death_prophet_Btn.setText(_translate("Form", "death_prophet"))
        self.obsidian_destroyer_Btn.setText(_translate("Form", "obsidian_destroyer"))
        self.crystal_maiden_Btn.setText(_translate("Form", "crystal_maiden"))
        self.silencer_Btn.setText(_translate("Form", "silencer"))
        self.queenofpain_btn.setText(_translate("Form", "queenofpain"))
        self.necrolyte_Btn.setText(_translate("Form", "necrolyte"))
        self.invoker_Btn.setText(_translate("Form", "invoker"))
        self.oracle_Btn.setText(_translate("Form", "oracle"))
        self.bane_Btn.setText(_translate("Form", "bane"))
        self.visage_Btn.setText(_translate("Form", "visage"))
        self.lina_Btn.setText(_translate("Form", "lina"))
        self.lion_Btn.setText(_translate("Form", "lion"))
        self.batrider_Btn.setText(_translate("Form", "batrider"))
        self.enigma_Btn.setText(_translate("Form", "enigma"))
        self.ancient_apparition_Btn.setText(_translate("Form", "ancient_apparition"))
        self.dark_willow_Btn.setText(_translate("Form", "dark_willow"))
        self.chen_Btn.setText(_translate("Form", "chen"))
        self.storm_spirit_Btn.setText(_translate("Form", "storm_spirit"))
        self.windrunner_Btn.setText(_translate("Form", "windrunner"))
        self.ogre_magi_Btn.setText(_translate("Form", "ogre_magi"))
        self.enchantress_Btn.setText(_translate("Form", "enchantress"))
        self.dark_seer_Btn.setText(_translate("Form", "dark_seer"))

